local M = {
	"nvim-treesitter/nvim-treesitter",
	dependencies = {
		"nvim-treesitter/nvim-treesitter-textobjects",
		"tree-sitter/tree-sitter-cpp",
		"tree-sitter-grammars/tree-sitter-arduino",
		"dlvandenberg/tree-sitter-angular",
		"virchau13/tree-sitter-astro",
	},
	build = ":TSUpdate",
	event = "VeryLazy",
	main = "nvim-treesitter.configs",
}

M.opts = {
	ensure_installed = {
		"lua",
		"dart",
		"luadoc",
		"tsx",
		"json",
		"css",
		"kotlin",
		"dart",
		"python",
		"javascript",
		"typescript",
		"solidity",
		"html",
		"css",
		"vue",
		"rust",
		"c",
		"cpp",
		"arduino",
		"angular",
		"astro",
		"asm",
		"bash",
		"cairo",
		"comment",
		"csv",
		"cuda",
		"dockerfile",
		"diff",
		"disassembly",
		"gdscript",
		"git_config",
		"git_rebase",
		"gitattributes",
		"gitcommit",
		"gitignore",
		"go",
		"godot_resource",
		"java",
		"markdown",
		"php",
		"phpdoc",
		"prisma",
		"requirements",
		"ruby",
		"rust",
		"scheme",
		"scss",
		"solidity",
		"sql",
		"swift",
		"vue",
		"xml",
		"yaml",
		"zathurarc",
	},
	autotag = {
		enable = true,
	},
	hightlight = {
		enable = true,
	},
	indent = {
		enable = true,
	},
	textobjects = {
		select = {
			enable = true,
			lookahead = true,
			keymaps = {
				["af"] = "@function.outer",
				["if"] = "@function.inner",
				["ac"] = "@conditional.outer",
				["ic"] = "@conditional.inner",
				["al"] = "@loop.outer",
				["il"] = "@loop.inner",
			},
		},
	},
}

return M
